### ISSUE TITLE
Questões sobre o projeto

### ISSUE THREAD

**Issue by ruthiel** [franciscobmacedo/frutafeia#5]
Olá @franciscobmacedo ,

Esta é um projeto pensado para a Fruta Feia?
Sou cliente e ando sempre a pensar em começar um projeto para dinamizar a facilitar o processo deles.

Estou disponível para ajudar.

Parabéns pela iniciativa.

**Comment by franciscobmacedo** [comment]
Viva, este projecto foi feito no ambito de um projecto da DSSG para optimizar a logistica e criação de cestas para a Fruta Feia utilizar internamente. Neste momento já não faço parte dele!

https://www.dssg.pt/en/projects/optimization-of-the-preparation-of-the-weekly-baskets-of-the-northern-hub-of-fruta-feia/
